[window]
dimensions = { columns = 122, lines = 30 }
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.8
#blur = true
decorations_theme_variant = "Dark"

[font]
normal = { family = "JetBrains Mono Nerdfont", style = "SemiBold" }
size = 16

[cursor]
style = { shape = "Underline", blinking = "On" }
